"""Add water management models

Revision ID: 933ade9f4842
Revises: 
Create Date: 2025-12-07 08:17:54.633560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933ade9f4842'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('guest', 'expert', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('water_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('resource_type', sa.Enum('lake', 'canal', 'reservoir', 'river', 'other', name='resourcetype'), nullable=False),
    sa.Column('water_type', sa.Enum('fresh', 'non_fresh', name='watertype'), nullable=True),
    sa.Column('fauna', sa.Enum('fish_bearing', 'non_fish_bearing', name='faunatype'), nullable=True),
    sa.Column('passport_date', sa.DateTime(), nullable=True),
    sa.Column('technical_condition', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('priority_level', sa.Enum('high', 'medium', 'low', name='prioritylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_objects_id'), 'water_objects', ['id'], unique=False)
    op.create_index(op.f('ix_water_objects_name'), 'water_objects', ['name'], unique=False)
    op.create_index(op.f('ix_water_objects_priority'), 'water_objects', ['priority'], unique=False)
    op.create_index(op.f('ix_water_objects_priority_level'), 'water_objects', ['priority_level'], unique=False)
    op.create_index(op.f('ix_water_objects_region'), 'water_objects', ['region'], unique=False)
    op.create_index(op.f('ix_water_objects_resource_type'), 'water_objects', ['resource_type'], unique=False)
    op.create_table('passport_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_object_id', sa.Integer(), nullable=False),
    sa.Column('document_title', sa.String(), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('general_info', sa.Text(), nullable=True),
    sa.Column('technical_params', sa.Text(), nullable=True),
    sa.Column('ecological_state', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['water_object_id'], ['water_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passport_texts_id'), 'passport_texts', ['id'], unique=False)
    op.create_index(op.f('ix_passport_texts_water_object_id'), 'passport_texts', ['water_object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passport_texts_water_object_id'), table_name='passport_texts')
    op.drop_index(op.f('ix_passport_texts_id'), table_name='passport_texts')
    op.drop_table('passport_texts')
    op.drop_index(op.f('ix_water_objects_resource_type'), table_name='water_objects')
    op.drop_index(op.f('ix_water_objects_region'), table_name='water_objects')
    op.drop_index(op.f('ix_water_objects_priority_level'), table_name='water_objects')
    op.drop_index(op.f('ix_water_objects_priority'), table_name='water_objects')
    op.drop_index(op.f('ix_water_objects_name'), table_name='water_objects')
    op.drop_index(op.f('ix_water_objects_id'), table_name='water_objects')
    op.drop_table('water_objects')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
